# Generated by Django 4.2.30 on 2026-08-02 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(max_length=50, unique=True)),
                ('driver', models.CharField(max_length=100)),
                ('latitude', models.FloatField(default=22.7196)),
                ('longitude', models.FloatField(default=75.8577)),
                ('route', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Delayed', 'Delayed'), ('Maintenance', 'Maintenance')], default='Active', max_length=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('cleanliness_score', models.IntegerField(default=90)),
                ('total_complaints', models.IntegerField(default=0)),
                ('resolved_complaints', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
