# Generated by Django 4.2.30 on 2026-08-02 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='latitude',
            field=models.FloatField(default=20.2961),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='longitude',
            field=models.FloatField(default=85.8245),
        ),
    ]
