# Generated by Django 4.2.30 on 2026-08-02 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='ward',
            field=models.CharField(blank=True, default='Vijay Nagar', max_length=100),
        ),
    ]
