# Generated by Django 4.2.30 on 2026-08-02 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Weekly Cleanliness Report', max_length=200)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('total_complaints', models.IntegerField(default=0)),
                ('resolved_count', models.IntegerField(default=0)),
                ('pending_count', models.IntegerField(default=0)),
                ('highest_category', models.CharField(default='Garbage Accumulation', max_length=100)),
                ('highest_risk_ward', models.CharField(default='Vijay Nagar', max_length=100)),
                ('summary_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hotspot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ward', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=150)),
                ('risk_level', models.CharField(choices=[('HIGH', 'High Risk'), ('MEDIUM', 'Medium Risk'), ('LOW', 'Low Risk')], default='MEDIUM', max_length=10)),
                ('complaint_count', models.IntegerField(default=0)),
                ('primary_category', models.CharField(default='Garbage Accumulation', max_length=100)),
                ('reason', models.TextField(help_text='AI explanation of why area is classified at this risk level')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PredictionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_text', models.TextField()),
                ('predicted_category', models.CharField(max_length=100)),
                ('predicted_priority', models.CharField(max_length=10)),
                ('confidence_score', models.FloatField(default=0.85)),
                ('user_accepted', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('ward', models.CharField(blank=True, max_length=100)),
                ('priority', models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='MEDIUM', max_length=10)),
                ('is_acknowledged', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
